### ISSUE TITLE
As a user, I can connect my polkadot account

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/collaboration#12]
- [x] Show connect button when no account connected
- [x] Show the account onchain identity or address if accounted
- [x] A user can disconnect or switch account

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=1282%3A7040

preview
![image](https://user-images.githubusercontent.com/59445675/134797006-4117a8ab-d91f-489b-92d2-b2f3a613c35d.png)
