### ISSUE TITLE
Fix font style

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#183]
- [x] Fixed

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=1145%3A5372

preview
![image](https://user-images.githubusercontent.com/59445675/137065848-9c4df6db-b431-45e3-9d2e-d9617c1c7c65.png)

**Comment by YoshiyukiSakura** [comment]
![image](https://user-images.githubusercontent.com/12393771/137073317-00ac2eb9-78a4-4c08-8548-9a5de329dbdc.png)
