### ISSUE TITLE
Implement page of 404

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#193]
- [x] Implemented

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=2392%3A190513

file
[bg-404.zip](https://github.com/opensquare-network/collaboration/files/7335857/bg-404.zip)

preview
![image](https://user-images.githubusercontent.com/59445675/137084684-213f5a0b-a755-4fc5-a7b0-daef818a49b1.png)

**Comment by hyifeng** [comment]
Refs #164

- [x] https://test.opensquare.io/space
- [ ] https://test.opensquare.io/space/statemine
- [ ] https://test.opensquare.io/space/statemine/1
