### ISSUE TITLE
Keep balance-of and quadratic-balance-of strategies at same time for current spaces

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/collaboration#256]
Currently we keep both of these 2 strategies for all spaces.

UI @Popoulosss 

- Show 2 strategies on the space home page
- Show voting results for all 2 strategies

Implementation @hyifeng (plz assign it to others if you are too busy)
- Backend compute the voting result for 2 strategies
- Show them on the proposal detail page

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=1773%3A164388

preview
![image](https://user-images.githubusercontent.com/59445675/137701551-217c3786-88bb-49d2-b323-090cc3d98bcc.png)

----

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=1999%3A16965

preview
![image](https://user-images.githubusercontent.com/59445675/137701727-05d1c7a5-a5d1-409b-ad7f-00b136ff508d.png)
