### ISSUE TITLE
Balance check enhancement

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/collaboration#324]
https://user-images.githubusercontent.com/2264908/140903960-ab8b15c5-557f-46bc-a146-2a3d75826b4f.mp4

1. Not show the error first
2. First show the balance loading status
3. If loading error, then show the error info
4. If loading ok, then if has not enough balance, show the no balance error, or show the balance

**Comment by Popoulosss** [comment]
- [ ] Implement loading effect

file
[loading.zip](https://github.com/opensquare-network/collaboration/files/7504304/loading.zip)

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=1754%3A114529

preview
![image](https://user-images.githubusercontent.com/59445675/140917160-fee77dc4-e3c0-4932-8a2e-24628bfe5bec.png)
