### ISSUE TITLE
Mark my vote

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#334]
- [x] Add a badge to my vote, follow the username
- [x] Pin my vote to the top of votes list, not affected by page turning

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=1208%3A5019

preview
![image](https://user-images.githubusercontent.com/59445675/142154958-30e0d3ea-770b-4b57-b982-b3b9c22af9cc.png)

**Comment by Popoulosss** [comment]
- [ ] Add loading effect to votes list (discussion list) when turning page or connect/disconnect wallet

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3270%3A15230

preview
![image](https://user-images.githubusercontent.com/59445675/142170285-717bce1a-4163-4bab-9858-7c16ec3e064c.png)

**Comment by hyifeng** [comment]
- [ ] My vote does not updated when user logout or connect wallet,
