### ISSUE TITLE
RMRK support

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#355]
file
[rmrk.zip](https://github.com/opensquare-network/collaboration/files/7589168/rmrk.zip)

preview
space
<img width="258" alt="截屏2021-11-23 23 29 20" src="https://user-images.githubusercontent.com/59445675/143053509-ad62e75f-1360-4937-a7e4-7eec1059a480.png">
icon
<img width="340" alt="截屏2021-11-23 23 29 31" src="https://user-images.githubusercontent.com/59445675/143053534-921d7705-c5ea-4b74-b9ed-ab30a5fd3cf7.png">

**Comment by wliyongfeng** [comment]
- [ ] Nav bar missed in RMRK proposal detail page
- [ ] We should support proxy vote for RMRK
- [ ] We have to implement creating a proposal with proxy account

**Comment by wliyongfeng** [comment]
![BJxCLXScTH](https://user-images.githubusercontent.com/2264908/143895291-173c0591-acb1-49b9-b919-ef95d8e1ece1.png)
![WGI19FrKbr](https://user-images.githubusercontent.com/2264908/143895335-36d9397c-70be-4e74-9ac4-bbcb68dff6b3.png)

**Comment by Popoulosss** [comment]
- [ ] Implement creating a proposal with proxy account

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3382%3A15604

preview
![image](https://user-images.githubusercontent.com/59445675/144010719-6565938d-2296-47a4-a4b6-227b67352f1e.png)
