### ISSUE TITLE
Implement creating a proposal with proxy account UI

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/collaboration#360]
figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3382%3A15604

preview
![image](https://user-images.githubusercontent.com/59445675/144011152-717cc8d0-4155-42c7-81b7-1224fb2cd746.png)

_Originally posted by @Popoulosss in https://github.com/opensquare-network/collaboration/issues/355#issuecomment-982391027_

**Comment by Popoulosss** [comment]
- [ ] Display balance whether it is enough or not
![image](https://user-images.githubusercontent.com/59445675/144834948-e212d7ae-7833-439c-b5a9-beaa9038124f.png)

- [ ] Fix UI style
![image](https://user-images.githubusercontent.com/59445675/144835048-cc875584-4b3c-44c3-9c2c-a89d180b6c02.png)

- [ ] Fix margin
![image](https://user-images.githubusercontent.com/59445675/144835557-1093bc0e-5af9-418b-a1eb-619590361304.png)
