### ISSUE TITLE
Create 'RMRK Curation' space

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/collaboration#402]
Logo:
![image](https://user-images.githubusercontent.com/2264908/148650690-40757a2c-801a-4e4b-a090-a885c3e519c9.png)

Name:
RMRK Curation

Threshold to create a proposal:
431 $RMRK

Threshold to vote:
keep it same with RMRK space

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3003%3A31641

preview
![image](https://user-images.githubusercontent.com/59445675/148667465-a451729f-b3ac-4876-b311-18a75348c851.png)
