### ISSUE TITLE
As a proposal author, I want to append some content to my proposal

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/collaboration#438]
1. I create a proposal
2. I find I have missed a important part
3. I click the append button, input the content to be appended, sign and submit it.

Note:

- The author can not append content to a closed proposal.

**Comment by favalos** [comment]
Hi @wliyongfeng,

I have been spending some time on this, but it is not clear how do you want to append data. 

Please take a look to the Draft pull request #619. 

Are you thinking to add a TextArea and literally append the data entered to the body? Or do you want to be able to edit any information in the Proposal?

I was thinking about it and the TextArea makes sense but what if the proposer wants to add another Option to the response?

Regards,

**Comment by wliyongfeng** [comment]
Hey @favalos , thanks for your time. Actually I haven't finally decided some details of this feature. Some consideration includes:
- We may not let the author append info at any time, maybe only in several hours after the creation.
- The author can still leave messages in the discussions.
- I can not decide whether this feature is real need for users.

I think you can stop your work about this issue. I'll leave details on this issue when I decide the details.

**Comment by wliyongfeng** [comment]
Final decision:

- [ ] The proposal author can append any items of message in the proposal active time.
- [ ] The button should be disabled when the proposal due date is over.

@Popoulosss Please design this feature.

**Comment by wliyongfeng** [comment]
Check https://github.com/opensquare-network/collaboration/issues/759 for the figma design.
