### ISSUE TITLE
Implement dotsama bias voting UI logic

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/collaboration#445]
- [x] Show bias voting only when there are 2 vote choices
- [x] Show options passing/failing when voting in progress
- [x] Show options passed/failed when voting is ended

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=1999%3A16965

preview
<img width="522" alt="image" src="https://user-images.githubusercontent.com/59445675/153538119-416281db-dffd-4732-8f16-117a55ff9078.png">

**Comment by Popoulosss** [comment]
- [ ] Change subtitle UI, remove serial number(It may be confused with the serial number of the voting option)

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/153538250-7a50bff7-08c2-49db-a349-b24a2e09c95e.png">

**Comment by Popoulosss** [comment]
- [ ] Show strategies(biased-voting) in the space page
- [ ] The maximum width of the text is 240px, f the text overflows and displays the ellipsis
- [ ] Show full information when hovering

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3989%3A19696

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/153568717-001b5b7e-88d4-44a7-b82c-90c7d29f2446.png">
