### ISSUE TITLE
Proposal voting summary on list page

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/collaboration#450]
Add an icon to proposal list page, that when we hover on the icon, a popup tooltip containing voting summary information will be displayed.

Voting summary have these information
1. The sum of voting balance for each choice.
2. Total voters count

- [x] Voting summary UI Design (@Popoulosss)
- [x] #459

**Comment by Popoulosss** [comment]
- [ ] When hovering over proposal card, show the icon, when hovering over the icon, displays the voting information. The tooltip displays up or down depending on the height of the position

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3658%3A22160


preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/153835741-7f346d3e-ad4d-4e82-83b7-899c4291f742.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/153835794-9fd29007-26c6-4351-bb48-3db895639d7e.png">
