### ISSUE TITLE
Optimize voting display

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#477]
figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3254%3A15503

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/154605088-0d4e9726-41b7-498e-af14-0cf3b213b40e.png">

**Comment by YoshiyukiSakura** [comment]
![image](https://user-images.githubusercontent.com/12393771/154918558-7fb9b762-c7fb-497c-b4a1-9d49a1a6bd31.png)
