### ISSUE TITLE
Fix font size

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#484]
- [x] Fix font to 14px

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=1145%3A5325

preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/154834796-caa993bf-8718-4e2d-8dc8-6184d50a4c14.png">

**Comment by YoshiyukiSakura** [comment]
![image](https://user-images.githubusercontent.com/12393771/154919240-39a3edb2-c399-4a42-9b96-f6058c5c452b.png)
