### ISSUE TITLE
New Wallet Connect to support multiple chains

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/collaboration#487]
- [x] UI Design (@Popoulosss )
- [x] Hide "Connect" from site root "/", and show when user enter a space
- [x] Show Chain selection in Connect popup
- [x] Store the connected address and chain per space (Each space has its connect information)

**Comment by Popoulosss** [comment]
Figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3658%3A22342

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/155052936-29e4c7ee-539e-46b4-9bed-3c35d656defb.png">
