### ISSUE TITLE
Create proposal on multiple chains

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/collaboration#488]
- [x] UI Design (@Popoulosss)
- [x] In Create proposal page, show multiple snapshot height (for each chain)
- [x] Check the proposal creator balance by chain
- [x] Save proposal creator with address and its chain
- [x] Able to get snapshot height by the selected date time for each chain

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=4235%3A35093

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/155078445-7d7b4569-51d4-4946-b4af-e247ccdbd548.png">
