### ISSUE TITLE
Date time to Snapshot height convert

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/collaboration#494]
- [ ] Create Bifrost/Karura/Moonriver backend services to serve time to block height convert ( Scan and save block head only )

**Comment by wliyongfeng** [comment]
@hyifeng Scan and save all the block head is not acceptable. 

Suppose:
1. `targetHeight = the wanted height`
2. `estimatedTime = estimated block time`
3. `expectedTime = expected target time`
4. `blockTime = the average time to produce one block`

A possible way:
1. Set `targetHeight = latest height`
2. Get the block time of `targetHeight`, and set it to `estimatedTime`.
3. If the gap between `estimatedTime` and `expectedTime` is smaller than for example `3 * blockTime`, then we use this block.
3. Estimate the target block height with each block time 
4. If the gap between `estimatedTime` and `expectedTime` is smaller than for example `3 * blockTime`, then we use this block.
4.
