### ISSUE TITLE
Add PolarisDAO space

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/collaboration#519]
- [x] The threshold is set to 40000 $ARIS
- [x] Logo is same with the one on statemine asset page https://statemine.statescan.io/asset/16
- [x] Currently only Statemine, maybe multiple chains when our multiple chain support is ready.

**Comment by Popoulosss** [comment]
file
[symbol&icon-polarisdao.zip](https://github.com/opensquare-network/collaboration/files/8138847/symbol.icon-polarisdao.zip)

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/155662107-0234e6b3-689d-4c14-8bb9-2a755a9c68b9.png">

**Comment by Popoulosss** [comment]
- [ ] Replace Kintsugi space image

file
[symbol-kintsugi.png.zip](https://github.com/opensquare-network/collaboration/files/8138852/symbol-kintsugi.zip)

**Comment by Popoulosss** [comment]
- [ ] Please replace the space image and icon

file
[polarisdao.zip](https://github.com/opensquare-network/collaboration/files/8142691/polarisdao.zip)
