### ISSUE TITLE
Display an ellipsis when text overflow in votes panel

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#612]
- [x] Done
[Related link](https://voting.opensquare.io/space/rmrk-curation/proposal/QmWrxbypXa88jWx8RfgsgL1qHpbeHtpL16amDxGWwkJB4c)

preview
username/identity
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/158329817-7ff6423b-6b36-4c8e-825c-ef034a419685.png">
content
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/158329826-03437262-47c5-40ee-9d49-31974e616e87.png">

**Comment by Popoulosss** [comment]
For username(address/identity), add underline when hover over it, show full text and address

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/160325792-a085b484-ee87-4d6b-a818-6b6cdef87dfd.png">

---

For plain text show full text and number

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/160325937-79b3b286-9b5b-4154-ac79-d77b36a14ea6.png">

**Comment by wliyongfeng** [comment]
![Fd5CZZkTkA](https://user-images.githubusercontent.com/2264908/165787327-7f8a9f29-0ee9-45e9-93a9-047017d0dd76.png)
Here we should show the full identity, but not the shorten address.
