### ISSUE TITLE
Support Centrifuge

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#617]
#### UI

- [ ] Icons
- [ ] SNS preview

files
[icons-centrifuge.zip](https://github.com/opensquare-network/collaboration/files/8301455/icons-centrifuge.zip)
[SNS-centrifuge.zip](https://github.com/opensquare-network/collaboration/files/8301428/SNS-centrifuge.zip)

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/158934954-f232c9d1-926d-4bdb-b93e-f28acf9e1770.png">

**Comment by wliyongfeng** [comment]
We will later integrate centrifuge para-chain directly.
