### ISSUE TITLE
Support Interlay

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#618]
#### UI

- [x] Icons
- [x] SNS preview

files
[icons-interlay.zip](https://github.com/opensquare-network/collaboration/files/8310724/icons-interlay.zip)
[imgs-sns-interlay.zip](https://github.com/opensquare-network/collaboration/files/8310725/imgs-sns-interlay.zip)

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/159151017-6b365bfc-1220-4e48-bdfc-857ff57f50e0.png">

**Comment by favalos** [comment]
Created a pull request for this issue #637

**Comment by Popoulosss** [comment]
Replace images

files
[icons-interlay-2.zip](https://github.com/opensquare-network/collaboration/files/8359706/icons-interlay-2.zip)
[imgs-sns-interlay-2.zip](https://github.com/opensquare-network/collaboration/files/8359707/imgs-sns-interlay-2.zip)
