### ISSUE TITLE
Fronted connect account with metamask

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/collaboration#644]
Tips:

- [x] Check whether metamask is installed and show error info when not
- [x] Show 'no account' info when detected no account
- [x] Show wrong network info message when network is not same with the chosen one
- [x] When detected user switched to other network, logout
- [x] When detected metamask account switched, logout

**Comment by Popoulosss** [comment]
In Moonriver or Moonbeam network(evm chain), user need to connect to metamask wallet.

[figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=4306%3A1504615)

preview

connect Polkadot.js
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/160542626-a08c7669-1d8d-4a62-9437-0466a2e8b4e9.png">

connect Metamask
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/160542664-23615809-be67-4bc5-9704-b4bbea8e0a71.png">

If metamask is in wrong network, pop up the toast of the network error
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/160385285-da7723d0-9eff-47e2-8e15-8d3ce7e10cfd.png">

If metamask doesnt't have an account (address), pop up the toast of the error
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/160385312-9aa1174c-c999-4b09-97b5-da9697341b49.png">

**Comment by wliyongfeng** [comment]
From metamask documentation:

> You should only initiate a connection request in response to direct user action, such as clicking a button. You should always disable the "connect" button while the connection request is pending. You should never initiate a connection request on page load.

We should update the account when clicking abuttong.
