### ISSUE TITLE
random snapshot height missing

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/collaboration#685]
# we have 5 chains  for [RMRK Curation](https://test.opensquare.io/space/rmrk-curation) space, but sometimes the server might not response all chains height, we should still show the chain name & let user know some chain height is missing(its not ready to post)

<img width="326" alt="image" src="https://user-images.githubusercontent.com/12393771/163789079-4667ec28-e891-4dbb-832f-bb74faa9678d.png">

**Comment by Popoulosss** [comment]
If the height is not obtained, display "-". Font color #A1A8B3

Preview
<img width="709" alt="image" src="https://user-images.githubusercontent.com/59445675/163789980-a203c70e-b70a-439f-acc1-f2a41ed08cdc.png">
