### ISSUE TITLE
As a user, I want to vote with my asset on Ethereum

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/collaboration#719]
Some projects still have assets as ERC20 on ethereum, and it will be nice that users can create/vote a proposal with that.

- [x] node-api config to support query from ethereum
- [x] backend init spaces script
- [x] fronted network support
- [x] Design

**Comment by Popoulosss** [comment]
Files
[icons-ethereum.zip](https://github.com/opensquare-network/collaboration/files/8554645/icons-ethereum.zip)
