### ISSUE TITLE
unify `<ChainIcon>` component with `@osn/common-ui`

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/collaboration#726]
#680

**Comment by wliyongfeng** [comment]
@2nthony 
https://github.com/opensquare-network/collaboration/pull/724. On this PR, we add crust network
https://github.com/opensquare-network/collaboration/pull/734. On this PR, we add ethereum.

**Comment by 2nthony** [comment]
https://github.com/opensquare-network/paid-qa/issues/470
