### ISSUE TITLE
Fix identity/username layout

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#778]
[Link](https://voting.opensquare.io/space/rmrk-curation/proposal/QmaagYqmU1xkgfjeCk8Wy65FDbm1xVm8Lt17dyKxjcCt1M)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/169982431-aa85bcc1-f0f3-4fd0-8887-7c161bb80ff3.png">

**Comment by 2nthony** [comment]
duplicated
