### ISSUE TITLE
As a proposal author, I want to terminate my proposal before the end date

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/collaboration#793]
There maybe various reasons:
- There are mis-leading or unclear information in my proposal.
- The proposal becomes meaningless for voting.

Plus:

- Only the author can do terminate

**Comment by Popoulosss** [comment]
Add a button to terminate the proposal, only for the proposer
Add terminated tag

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=10440%3A45523)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/172121014-22503c24-777b-4844-a51d-5d2b70c9ce7c.png">

**Comment by 2nthony** [comment]
- only the author can `terminate`
- double check modal(dialog), generate 5 random characters to double check.

**Comment by Popoulosss** [comment]
- Add loading status

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/173530494-d47529f8-6c58-4b44-a62a-b738a367a674.png">

**Comment by wliyongfeng** [comment]
Review suggestion:
- Sign data should have a field to show it's a termination action. @hyifeng
