### ISSUE TITLE
As a proposal author, I want to set a banner for my proposal

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/collaboration#807]
- This banner can be shown on the SNS like twitter.
- It will be shown on the proposal content.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=10661%3A90046)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/174552633-78347231-2452-4e1f-8922-bbb27cb8dec5.png">

**Comment by Popoulosss** [comment]
Figma link

- Banner display before description in proposal detail page, and will not be collapsed
- Max width

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/174554769-38e966a8-34ca-41b0-b4e7-1c1df3e090fe.png">

**Comment by YoshiyukiSakura** [comment]
what about proposal list view?

**Comment by hyifeng** [comment]
```javascript
const fs = require("fs");
const axios = require("axios");
const FormData = require("form-data");

async function uploadFile(token) {
  const formdata = new FormData();
  formdata.append(
    'banner',
    fs.readFileSync("/home/path/to/image/xxx.jpg"),
    {
      contentType: 'image/jpg',
      name: 'banner',
      filename: "xxx.jpg",
    }
  );

  try {
    let result = await axios.post(
      'http://127.0.0.1:8081/files/upload',
      formdata,
      {
        headers: formdata.getHeaders(),
      }
    );
    console.log(result);

  } catch (e) {
    console.log(e.response.data);
  }
}

```
