### ISSUE TITLE
Support DotSama

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#822]
Files
[icons-dotsama.zip](https://github.com/opensquare-network/collaboration/files/8955381/icons-dotsama.zip)
[imgs-sns-preview.zip](https://github.com/opensquare-network/collaboration/files/8955383/imgs-sns-preview.zip)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/174969807-1a9f873b-f9f3-47dc-a4d0-af92af6e4f6f.png">

**Comment by Popoulosss** [comment]
- Add icon to symbol, link to(TBD)
- Hover effect

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=10708%3A49274)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/174970745-77527235-63e3-4e7c-98f4-adac6de28443.png">

**Comment by Popoulosss** [comment]
- Modify layout

Preview
![image](https://user-images.githubusercontent.com/59445675/174971128-b55b2ef4-9162-48c8-8b60-89c2afb69a96.png)

**Comment by wliyongfeng** [comment]
> * Modify layout
> 
> Preview <img alt="image" width="320" src="https://user-images.githubusercontent.com/59445675/174971438-9b144b23-05fc-42ea-ac72-f1e188cad74c.png">

@Popoulosss Please create another issue for this problem.
