### ISSUE TITLE
Replace voting option with serial number in mobile layout

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#840]
Figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3658%3A22300

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/176678255-004b2531-c601-4a6b-a78c-553423118b5a.png">

**Comment by YoshiyukiSakura** [comment]
done
![image](https://user-images.githubusercontent.com/12393771/182337559-2fbdc205-d06d-42ff-9ac6-0379256885a0.png)
