### ISSUE TITLE
keeps `@` symbol to mentioned identity user

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/collaboration#846]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/19513289/177138369-7baed216-675e-43c9-
95e5-6d918981dd47.png">

**Comment by Popoulosss** [comment]
- Display `@` symbol in front of the identity or address
- Need to display the chain icon 

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=11052%3A49370)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/177240741-2e7b862d-7471-4e1d-a694-022796126eb1.png">
