### ISSUE TITLE
Fix display of identity

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/collaboration#847]
[Link](https://voting.opensquare.io/space/rmrk-curation/proposal/QmcuwF4JGZMRXiM71VL3PfEx4YCQBe9mfuyHC2NGNyCf46)

- Remove margin top of avatar icon

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/177238649-47d96969-1b29-4881-a4a0-9a47f171040f.png">

- Add margin right 8px to avatar of moonbeam(ETH)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/177242817-b37a3d6e-bfb8-4d8d-8a8f-451df2cea592.png">

**Comment by 2nthony** [comment]
use common ui `IdentityUser.js` compoennt

**Comment by YoshiyukiSakura** [comment]
Steps:
0. switch to branch `fixIdentityDisplay`
1. set .env 
```
NEXT_PUBLIC_API_END_POINT=https://voting.opensquare.io/
NEXT_PUBLIC_BACKEND_API_END_POINT=https://voting.opensquare.io/
```
2. alter nextAPI.js  
```
export const ssrNextApi = new Api(
  new URL(
    `/api/`,
    process.env.NEXT_PUBLIC_BACKEND_API_END_POINT ||
      "https://test.opensquare.io/"
  ).href
);
```

3. access http://127.0.0.1:8001/space/rmrk-curation/proposal/QmcuwF4JGZMRXiM71VL3PfEx4YCQBe9mfuyHC2NGNyCf46

and got this
![image](https://user-images.githubusercontent.com/12393771/183048442-7e7277a8-9e8c-4c03-a0e2-11afe0a402c5.png)
