### ISSUE TITLE
As a voter, I want my delegatee I set on-chain vote for me

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/collaboration#890]
- Conviction won't work
- Only the delegated balance work
- If I vote directly, the delegated balance should be subtracted from my total balance

**Comment by wliyongfeng** [comment]
#936 add api to get democracy delegators.

**Comment by Popoulosss** [comment]
- [ ] [Show the delegated vote record in votes list and add 'Delegation' tag](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3658-24422&t=40cNvtLAjgKvQg4a-11)
- [ ] [Show the delegation type in proposal detail page](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3658-22336&t=40cNvtLAjgKvQg4a-11)
- [ ] [Modify the space information card](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=8478-39907&t=40cNvtLAjgKvQg4a-11), refer to space summary card in create space process
   - [ ] Modify the layout
   - [ ] Show the proposal threshold and delegation type, categorize into 'Configures'
   - [ ] Change the 'Networks' to 'Assets', layout refer to space summary card in create space process
- [ ] If user‘s votes have delegated to another address, user cannot vote directly, [disabled the vote options and show the reason](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=13828-67761&t=40cNvtLAjgKvQg4a-11)

preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/231052893-832eb938-07ff-4d80-a0bb-d77736d93a3e.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/231052611-ba938eca-0c6d-49b3-be16-bc4fa7cf83db.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/231052956-9070c145-0a69-4107-8394-b966cf7f95e3.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/231052542-a01c6674-44ca-412f-b875-4b71e789b30c.png">

**Comment by Popoulosss** [comment]
Update

---

- [ ] Remove 'Delegation' from 'Configures'
- [ ] Show delegation type for a single asset

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=8478-39907&t=zGERCa4cYyIrjahK-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/231936773-fbd34158-6bf7-4168-b7bd-75ac9a92713c.png">
