### ISSUE TITLE
Allow users to join spaces and receive space notifications

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/collaboration#898]
Allow users to join spaces and receive space notifications

- [x] UI design (@Popoulosss )
- [ ] Implement
  - [ ] Add notification icon to top left of the header
  - [ ] Implement popup notification preview modal
  - [ ] Add notification detail page
  - [ ] and more...

**Comment by Popoulosss** [comment]
- [ ] When hovering on the space card, show the book icon if connected wallet in the correct network
- [ ] Implement hover, loading and active effect of book icon
- [ ] Display tooltips when hovering on the book icon
- [ ] Implement 'Join space' feature in space page
- [ ] Implement notification page and message panel

Figma link
[Voting homepage](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=12673%3A52554&viewport=2257%2C-4643%2C0.43)
[Space detial page](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=12774%3A63274)
[Notification page](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=12669%3A52861&viewport=1358%2C-4411%2C0.42)

**Comment by Popoulosss** [comment]
- [ ] Remove items' pre-icon in the header

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=12673%3A52557)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/197154290-d2a744fc-2d6e-4e2b-9b9d-a2d2d493d4f8.png">
