### ISSUE TITLE
Check if allow to publish proposal for the current account

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/collaboration#92]
Allow to publish proposal only when the current account has the required minimum balance at snapshot height.

![image](https://user-images.githubusercontent.com/6297057/136639258-f7772331-e7fb-4fde-8b7c-f7cb58c448c2.png)

**Comment by Popoulosss** [comment]
publish threshold:
polkadot 1 DOT
Kusama 0.01 KSM
Karura 1 KAR
Khala 10 PHA
@YoshiyukiSakura
